
DROP TABLE IF EXISTS COMPANY;
CREATE TABLE COMPANY
       (ID TEXT PRIMARY KEY     NOT NULL,
       NAME           TEXT    NOT NULL,
       AGE            INT     NOT NULL,
       ADDRESS        VARCHAR(50),
       SALARY         REAL);

DROP TABLE IF EXISTS video;
CREATE TABLE video (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(64),
  url VARCHAR(256),
  describe VARCHAR(256),
  thumb VARCHAR(256)
);